name: Build Linux release

on:
  release:
    types: created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: node version ${{ github.event.release.tag_name }}
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv target/release/corinth target/release/corinth-linux-${{ github.event.release.tag_name }}
      - name: Attach to ${{ github.event.release.tag_name }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/corinth-linux-${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
