name: Unit tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build corinth
      run: cargo build --verbose
    - name: Install test dependencies
      run: npm ci
      working-directory: test
    - name: Test
      uses: nick-invision/retry@v1
      with:
        timeout_minutes: 4
        max_attempts: 3
        command: npm test
